# .github/workflows/terraform.yml
name: Terraform CI/CD

on:
  push:
  pull_request:

on:
  workflow_dispatch:

 # define AWS_* env vars once, for every step in this job
env:
  AWS_REGION: eu-west-1

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token:     ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region:            ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.11.4

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format & Validate
        run: |
          terraform fmt -check
          terraform validate

      - name: Terraform Plan
        id: plan
        run: terraform plan -input=false -out=plan.tfplan

      - name: Terraform Apply
        run: terraform apply -input=false plan.tfplan

      - name: Cleanup Workspace
        if: always()
        run: rm -rf .terraform .terraform.lock.hcl plan.tfplan
